// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kzkatsDCvzPQVqDSnS1EKs
// Component: j3Hkwh0b7L
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import ChatListItem from "../../ChatListItem"; // plasmic-import: qgrz47A8td/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_plasmic_whats_app_clone.module.css"; // plasmic-import: kzkatsDCvzPQVqDSnS1EKs/projectcss
import sty from "./PlasmicChatList.module.css"; // plasmic-import: j3Hkwh0b7L/css

export const PlasmicChatList__VariantProps = new Array();

export const PlasmicChatList__ArgProps = new Array();

function PlasmicChatList__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <ChatListItem
        className={classNames("__wab_instance", sty.chatListItem__w12Ob)}
      />

      <ChatListItem
        className={classNames("__wab_instance", sty.chatListItem__zKxRq)}
      />

      <ChatListItem
        className={classNames("__wab_instance", sty.chatListItem__xK9Hf)}
      />

      <ChatListItem
        className={classNames("__wab_instance", sty.chatListItem__x5RGg)}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicChatList__ArgProps,
      internalVariantPropNames: PlasmicChatList__VariantProps
    });

    return PlasmicChatList__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicChatList";
  } else {
    func.displayName = `PlasmicChatList.${nodeName}`;
  }
  return func;
}

export const PlasmicChatList = Object.assign(
  // Top-level PlasmicChatList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicChatList
    internalVariantProps: PlasmicChatList__VariantProps,
    internalArgProps: PlasmicChatList__ArgProps
  }
);

export default PlasmicChatList;
/* prettier-ignore-end */
