// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kzkatsDCvzPQVqDSnS1EKs
// Component: _Bch9VQnC0
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_plasmic_whats_app_clone.module.css"; // plasmic-import: kzkatsDCvzPQVqDSnS1EKs/projectcss
import sty from "./PlasmicChatMessage.module.css"; // plasmic-import: _Bch9VQnC0/css

export const PlasmicChatMessage__VariantProps = new Array("isSend");

export const PlasmicChatMessage__ArgProps = new Array("message", "createdAt");

function PlasmicChatMessage__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root,
        { [sty.rootisSend]: hasVariant(variants, "isSend", "isSend") }
      )}
    >
      {true ? (
        <div
          className={classNames(projectcss.all, sty.freeBox__e9KDv, {
            [sty.freeBoxisSend__e9KDvj3Pkn]: hasVariant(
              variants,
              "isSend",
              "isSend"
            )
          })}
        >
          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text,
              { [sty.textisSend]: hasVariant(variants, "isSend", "isSend") }
            )}
          >
            {"username"}
          </div>

          <div
            className={classNames(projectcss.all, sty.freeBox__fSykl, {
              [sty.freeBoxisSend__fSyklj3Pkn]: hasVariant(
                variants,
                "isSend",
                "isSend"
              )
            })}
          >
            {p.renderPlasmicSlot({
              defaultContents:
                "Hello There, blah blah blah. I hope you are doing great",
              value: args.message
            })}

            <div
              className={classNames(projectcss.all, sty.freeBox__fQwB0, {
                [sty.freeBoxisSend__fQwB0J3Pkn]: hasVariant(
                  variants,
                  "isSend",
                  "isSend"
                )
              })}
            >
              <div className={classNames(projectcss.all, sty.freeBox___0AjBd)}>
                {p.renderPlasmicSlot({
                  defaultContents: "Time",
                  value: args.createdAt,
                  className: classNames(sty.slotTargetCreatedAt)
                })}
              </div>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "text"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicChatMessage__ArgProps,
      internalVariantPropNames: PlasmicChatMessage__VariantProps
    });

    return PlasmicChatMessage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicChatMessage";
  } else {
    func.displayName = `PlasmicChatMessage.${nodeName}`;
  }
  return func;
}

export const PlasmicChatMessage = Object.assign(
  // Top-level PlasmicChatMessage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicChatMessage
    internalVariantProps: PlasmicChatMessage__VariantProps,
    internalArgProps: PlasmicChatMessage__ArgProps
  }
);

export default PlasmicChatMessage;
/* prettier-ignore-end */
