// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kzkatsDCvzPQVqDSnS1EKs
// Component: 3EZolvVuQD
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Avatar from "../../Avatar"; // plasmic-import: gM35gl7eyM/component
import TextInput from "../../TextInput"; // plasmic-import: 6jNi7LUNkWm/component
import Button from "../../Button"; // plasmic-import: xYVXj1SpLX8/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_plasmic_whats_app_clone.module.css"; // plasmic-import: kzkatsDCvzPQVqDSnS1EKs/projectcss
import sty from "./PlasmicUserProfile.module.css"; // plasmic-import: 3EZolvVuQD/css

export const PlasmicUserProfile__VariantProps = new Array();

export const PlasmicUserProfile__ArgProps = new Array();

function PlasmicUserProfile__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <h3
        data-plasmic-name={"h3"}
        data-plasmic-override={overrides.h3}
        className={classNames(
          projectcss.all,
          projectcss.h3,
          projectcss.__wab_text,
          sty.h3
        )}
      >
        {"User Profile"}
      </h3>

      <Avatar
        data-plasmic-name={"avatar"}
        data-plasmic-override={overrides.avatar}
        className={classNames("__wab_instance", sty.avatar)}
        fullWidth={true}
      />

      <TextInput
        data-plasmic-name={"firstNameInput"}
        data-plasmic-override={overrides.firstNameInput}
        className={classNames("__wab_instance", sty.firstNameInput)}
        placeholder={"First Name"}
      />

      <TextInput
        data-plasmic-name={"lastNameInput"}
        data-plasmic-override={overrides.lastNameInput}
        className={classNames("__wab_instance", sty.lastNameInput)}
        placeholder={"Last Name"}
      />

      <Button
        data-plasmic-name={"button"}
        data-plasmic-override={overrides.button}
        className={classNames("__wab_instance", sty.button)}
        color={"green"}
      >
        {"Update Profile"}
      </Button>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "h3", "avatar", "firstNameInput", "lastNameInput", "button"],
  h3: ["h3"],
  avatar: ["avatar"],
  firstNameInput: ["firstNameInput"],
  lastNameInput: ["lastNameInput"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicUserProfile__ArgProps,
      internalVariantPropNames: PlasmicUserProfile__VariantProps
    });

    return PlasmicUserProfile__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUserProfile";
  } else {
    func.displayName = `PlasmicUserProfile.${nodeName}`;
  }
  return func;
}

export const PlasmicUserProfile = Object.assign(
  // Top-level PlasmicUserProfile renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h3: makeNodeComponent("h3"),
    avatar: makeNodeComponent("avatar"),
    firstNameInput: makeNodeComponent("firstNameInput"),
    lastNameInput: makeNodeComponent("lastNameInput"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicUserProfile
    internalVariantProps: PlasmicUserProfile__VariantProps,
    internalArgProps: PlasmicUserProfile__ArgProps
  }
);

export default PlasmicUserProfile;
/* prettier-ignore-end */
